openapi: 3.0.1
info:
  title: API продавца
  version: '1.8'
  x-logo:
    url: ./lang/ru.png
    altText: ru
    href: ./en/index.html
  description: "# Общее описание\n<style> .version {\n  border: 0.1rem #b3b3b3 solid;\n\
    \  background-color: #F9F9F9;\n  color: #32329FE6;\n  height: 25px;\n  width:\
    \ 150px;\n  text-align: center\n}, </style> <style> .warning {\n  border: 1.6rem\
    \ #b3b3b3 solid;\n  background-color: #F9F9F9;\n  color: #247706;\n  text-align:\
    \ center\n} </style> <style> .langChange {\n  text-align: left;\n  padding: 2px\
    \ 222px 2px 18px;\n} </style>\n\nWildberries API предоставляет продавцам возможность\
    \ управления магазином и получения оперативной и статистической информации по\
    \ протоколу HTTP RestAPI. <br> Описание API предоставляется в формате [Swagger](https://swagger.io/)\
    \ (Open API) и может быть использовано для импорта в другие инструменты (такие\
    \ как PostMan) или генерации клиентского кода на различных языках программирования\
    \ с помощью [Swagger CodeGen](https://swagger.io/tools/swagger-codegen/)\n\n<ul>\
    \ <li> Описание в оригинальном swagger-формате <a href=\"/swagger\">swagger</a>\
    \ <li> OpenAPI-файл <a href=\"/swagger.yaml\">swagger.yaml</a> </ul>\n\n<br> Для\
    \ ручной проверки API вы можете использовать: <ul> <li> Под ОС Windows - [PostMan](https://www.postman.com/)\
    \ <li> Под ОС Linux - [curl](https://curl.se/)  </ul> <br>\n\n## Поддержка\nТехническая\
    \ поддержка осуществляется через диалоги в личном кабинете продавца. При создании\
    \ нового обращения в техподдержку используйте категорию API.\n<br> Новости и изменения,\
    \ касающиеся API, публикуются в [новостной ленте Wildberries](https://seller.wildberries.ru/news).\n\
    <br> Также готовятся к публикации Release Notes по API на сайте.  После их выхода\
    \ будет сделан соответствующий анонс. <br> <br> <br>\n\n## Авторизация\nАвторизация\
    \ осуществляется по токенам API, которые  владелец личного кабинета (главный пользователь)\
    \ самостоятельно\n генерирует в разделе \n [Профиль --> Настройки --> Доступ к\
    \ новому API](https://seller.wildberries.ru/supplier-settings/access-to-new-api).\n\
    <br>Обратите внимание, что токен отображается ТОЛЬКО в момент создания. Его надо\
    \ сохранить, потому что больше его отобразить будет нельзя. <br>Созданный токен\
    \ следует добавлять в каждый запрос, прибавляя к запросу заголовок (http-header)\
    \ формата `Authorization: .........`. <br> <br>Внимание! Изменился домен для методов\
    \ статистики, актуальный: https://statistics-api.wildberries.ru <br> <br> <br>\n\
    ## Форматы\n### Дата и время\nВо всех методах API статистики дата и время передаются\
    \ в формате [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339).  <br> В\
    \ большинстве случаев вы можете передать дату или дату со временем. Если время\
    \ не указано, оно принимается равным 00:00:00. Время можно указывать с точностью\
    \ до секунд или миллисекунд.  Литера `Z` в конце строки означает часовой пояс\
    \ UTC. При ее отсутствии время считается в часовом поясе МСК (UTC+3). <br> Примеры:\
    \ <ul> <li> `2019-06-20` <li> `2019-06-20T00:00:00Z` <li> `2019-06-20T23:59:59`\
    \ <li> `2019-06-20T00:00:00.12345Z` <li> `2019-06-20T00:00:00.12345` <li> `2017-03-25T00:00:00`\
    \ </ul> <br>\n## Обновления\n#### 2023.02.14 v1.8\n  \nДобавлено описание API\
    \ рекомендаций\n#### 2023.01.13 v1.7\n  \nДобавлено описание API рекламы\n####\
    \ 2022.12.21 v1.6\nДобавлена инструкция по загрузке статистики в Excel\n#### 2022.12.15\
    \ v1.5 \nНовая авторизация для методов API статистики 2022.12.15 в v1.5:\n####\
    \ 2022.10.31 v1.4 \nМетод будет отключен 2022.10.31 в v1.4: <ul> <li> `/content/v1/cards/list`\
    \ </ul>\n\n#### 2022.09.20 v1.2 \nВ связи с переходом на новое API Контента старые\
    \ методы будут отключены. К их числу относятся: <ul> <li> `/card/*` <li> `/api/v1/config/*`\
    \ <li> `/api/v1/directory/*` </ul>\nДанные методы теперь возвращают код 404. \
    \ Новое API Контента описано в данном документе в разделах Контент / * <br> <br>\n"
security:
  - HeaderApiKey: [ ]
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
  parameters:
    dateFrom:
      in: query
      name: dateFrom
      schema:
        type: string
        format: date
      required: true
      description: 'Дата в формате RFC3339. Можно передать дату или дату со временем.  Время
        можно указывать с точностью до секунд или миллисекунд.  Литера `Z` в конце
        строки означает, что время передается в UTC-часовом поясе.  При ее отсутствии
        время считается в часовом поясе МСК (UTC+3). <br>Примеры: <ul> <li> `2019-06-20`
        <li> `2019-06-20T00:00:00Z` <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345Z`
        <li> `2019-06-20T00:00:00.12345` <li> `2017-03-25T00:00:00` </ul>
        '
    flag:
      in: query
      name: flag
      schema:
        type: integer
        default: 0
    Warehouse:
      name: warehouse
      in: path
      required: true
      description: Идентификатор склада продавца
      schema:
        type: integer
        example: 1234
  schemas:
    OrdersItem:
      type: object
      properties:
        gNumber:
          type: string
          maxLength: 50
          description: Номер заказа. Объединяет все позиции одного заказа.
        date:
          type: string
          description: Дата и время заказа. Это поле соответствует параметру `dateFrom`
            в запросе, если параметр `flag=1`. Если часовой пояс не указан, то берется
            Московское время UTC+3.
        lastChangeDate:
          type: string
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе, если параметр `flag=0` или не указан.
            Если часовой пояс не указан, то берется Московское время UTC+3.
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул поставщика
        techSize:
          type: string
          maxLength: 30
          description: Размер
        barcode:
          type: string
          maxLength: 30
          description: Бар-код
        totalPrice:
          type: number
          description: Цена до согласованной итоговой скидки/промо/спп. Для получения
            цены со скидкой можно воспользоваться формулой `priceWithDiscount = totalPrice
            * (1 - discountPercent/100)`
        discountPercent:
          type: integer
          description: Согласованный итоговый дисконт. Будучи примененным к `totalPrice`,
            даёт сумму к оплате.
        warehouseName:
          type: string
          maxLength: 50
          description: Название склада отгрузки
        oblast:
          type: string
          maxLength: 200
          description: Область
        incomeID:
          type: integer
          description: Номер поставки (от продавца на склад)
        odid:
          type: integer
          description: Уникальный идентификатор позиции заказа. Может использоваться
            для поиска соответствия между заказами и продажами.
        nmId:
          type: integer
          description: Код WB
        subject:
          type: string
          maxLength: 50
          description: Предмет
        category:
          type: string
          maxLength: 50
          description: Категория
        brand:
          type: string
          maxLength: 50
          description: Бренд
        isCancel:
          type: boolean
          description: Отмена заказа. true - заказ отменен до оплаты.
        cancel_dt:
          type: string
          description: Дата и время отмены заказа. Если заказ не был отменен, то `"0001-01-01T00:00:00"`.
            Если часовой пояс не указан, то берется Московское время UTC+3.
        sticker:
          type: string
          description: Цифровое значение стикера, который клеится на товар в процессе
            сборки заказа по системе Маркетплейс.
        srid:
          type: string
          description: 'Уникальный идентификатор заказа, функционально аналогичный
                `odid`/`rid`.  Данный параметр введен в июле''22 и в течение переходного
                периода может быть заполнен не во всех ответах. Примечание для работающих
                по системе Маркетплейс: `srid` равен `rid` в ответе на метод `GET /api/v2/orders`.'
    SalesItem:
      type: object
      properties:
        gNumber:
          type: string
          maxLength: 50
          description: Номер заказа. Объединяет все позиции одного заказа.
        date:
          type: string
          description: Дата и время продажи. Это поле соответствует параметру `dateFrom`
            в запросе, если параметр `flag=1`. Если часовой пояс не указан, то берется
            Московское время UTC+3.
        lastChangeDate:
          type: string
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе, если параметр `flag=0` или не указан.
            Если часовой пояс не указан, то берется Московское время UTC+3.
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул поставщика
        techSize:
          type: string
          maxLength: 30
          description: Размер
        barcode:
          type: string
          maxLength: 30
          description: Бар-код
        totalPrice:
          type: number
          description: Цена до согласованной скидки/промо/спп. Для получения цены
            со скидкой можно воспользоваться формулой `priceWithDiscount = totalPrice
            * (1 - discountPercent/100)`
        discountPercent:
          type: integer
          description: Согласованный итоговый дисконт
        isSupply:
          type: boolean
          description: Договор поставки
        isRealization:
          type: boolean
          description: Договор реализации
        promoCodeDiscount:
          type: number
          description: Скидка по промокоду
        warehouseName:
          type: string
          maxLength: 50
          description: Название склада отгрузки
        countryName:
          type: string
          maxLength: 200
          description: Страна
        oblastOkrugName:
          type: string
          maxLength: 200
          description: Округ
        regionName:
          type: string
          maxLength: 200
          description: Регион
        incomeID:
          type: integer
          description: Номер поставки (от продавца на склад)
        saleID:
          type: string
          maxLength: 15
          description: 'Уникальный идентификатор продажи/возврата. <ul>  <li> `SXXXXXXXXXX`
                — продажа  <li> `RXXXXXXXXXX` — возврат  <li> `DXXXXXXXXXXX` — доплата
                <li> `AXXXXXXXXX` – сторно продаж (все значения полей как у продажи, но
                поля с суммами и кол-вом с минусом как в возврате) <li> `BXXXXXXXXX` -
                сторно возврата (все значения полей как у возврата, но поля с суммами
                и кол-вом с плюсом, в противоположность возврату) </ul>'
        odid:
          type: integer
          description: Уникальный идентификатор позиции заказа. Может использоваться
            для поиска соответствия между заказами и продажами.
        spp:
          type: number
          format: float
          description: Согласованная скидка постоянного покупателя
        forPay:
          type: number
          description: К перечислению поставщику
        finishedPrice:
          type: number
          description: Фактическая цена заказа с учетом всех скидок
        priceWithDisc:
          type: number
          description: Цена, от которой считается вознаграждение поставщика `forpay`
            (с учетом всех согласованных скидок)
        nmId:
          type: integer
          description: Код WB
        subject:
          type: string
          maxLength: 50
          description: Предмет
        category:
          type: string
          maxLength: 50
          description: Категория
        brand:
          type: string
          maxLength: 50
          description: Бренд
        isStorno:
          type: integer
          description: Для сторно-операций `1`, для остальных `0`
        sticker:
          type: string
          description: Цифровое значение стикера, который клеится на товар в процессе
            сборки заказа по системе Маркетплейс.
        srid:
          type: string
          description: 'Уникальный идентификатор заказа, функционально аналогичный
                `odid`/`rid`.  Данный параметр введен в июле''22 и в течение переходного
                периода может быть заполнен не во всех ответах. Примечание для работающих
                по системе Маркетплейс: `srid` равен `rid` в ответе на метод `GET /api/v2/orders`.'
    ProductAttributesDictionaryValue:
      type: object
      properties:
        dictionaryValueId:
          type: integer
        value:
          type: string
    ProductAttributesComplexAttribute:
      type: object
      properties:
        attribute_id:
          type: integer
          description: Идентификатор характеристики.
        complex_id:
          type: integer
          description: Идентификатор характеристики, которая поддерживает вложенные свойства. Например, у характеристики «Процессор» есть вложенные характеристики «Производитель» и «L2 Cache». У каждой из вложенных характеристик может быть несколько вариантов значений.
        values:
          type: array
          items:
            $ref: '#/components/schemas/ProductAttributesDictionaryValue'
    ProductAttributesImage:
      type: object
      properties:
        default:
          type: boolean
        file_name:
          type: string
        index:
          type: integer
    ProductAttribute:
      type: object
      properties:
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/ProductAttributesComplexAttribute'
        barcode:
          type: string
          description: Штрихкод.
        category_id:
          type: integer
          description: Идентификатор категории.
        color_image:
          type: string
          description: Маркетинговый цвет.
        complex_attributes:
          type: array
          items:
            $ref: '#/components/schemas/ProductAttributesComplexAttribute'
        depth:
          type: integer
          description: Глубина.
        dimension_unit:
          type: string
          description: Единица измерения габаритов
        height:
          type: integer
          description: Высота упаковки.
        id:
          type: integer
          description: Идентификатор характеристики товара.
        image_group_id:
          type: string
          description: Идентификатор для последующей пакетной загрузки изображений.
        images:
          type: array
          items:
            $ref: '#/components/schemas/ProductAttributesImage'
        name:
          type: string
          description: Название товара. До 500 символов.
        offer_id:
          type: string
          description: Идентификатор товара в системе продавца — артикул.
        weight:
          type: integer
          description: Вес товара в упаковке.
        weight_unit:
          type: string
          description: Единица измерения веса.
        width:
          type: integer
          description: Ширина упаковки.
    ProductInfo:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        offer_id:
          type: string
        barcode:
          type: string
        barcodes:
          type: array
          items:
            type: string
        buybox_price:
          type: string
        category_id:
          type: integer
        created_at:
          type: string
        currency_code:
          type: string
        marketing_price:
          type: string
        old_price:
          type: string
        min_price:
          type: string
        vat:
          type: string
        fbo_sku:
          type: integer
    ProductAttributeFilterFilter:
      type: object
      properties:
        offer_id:
          type: array
          items:
            type: string
        product_id:
          type: array
          items:
            type: integer
        visibility:
          type: string
          enum:
            - ALL #все товары, кроме архивных.
            - VISIBLE # товары, которые видны покупателям.
            - INVISIBLE
            - EMPTY_STOCK # товары, у которых не указано наличие.
            - NOT_MODERATED # товары, которые не прошли модерацию.
            - MODERATED # товары, которые прошли модерацию.
            - DISABLED # товары, которые видны покупателям, но недоступны к покупке.
            - STATE_FAILED # товары, создание которых завершилось ошибкой.
            - READY_TO_SUPPLY # товары, готовые к поставке.
            - VALIDATION_STATE_PENDING # товары, которые проходят проверку валидатором на премодерации.
            - VALIDATION_STATE_FAIL # товары, которые не прошли проверку валидатором на премодерации.
            - VALIDATION_STATE_SUCCESS # товары, которые прошли проверку валидатором на премодерации.
            - TO_SUPPLY # товары, готовые к продаже.
            - IN_SALE # товары в продаже.
            - REMOVED_FROM_SALE # товары, скрытые от покупателей.
            - BANNED # заблокированные товары.
            - OVERPRICED # товары с завышенной ценой.
            - CRITICALLY_OVERPRICED # товары со слишком завышенной ценой.
            - EMPTY_BARCODE # товары без штрихкода.
            - BARCODE_EXISTS # товары со штрихкодом.
            - QUARANTINE # товары на карантине после изменения цены более чем на 50%.
            - ARCHIVED # товары в архиве.
            - OVERPRICED_WITH_STOCK # товары в продаже со стоимостью выше, чем у конкурентов.
            - PARTIAL_APPROVED # товары в продаже с пустым или неполным описанием.
            - IMAGE_ABSENT # товары без изображений.
            - MODERATION_BLOCK # товары, для которых заблокирована модерация.
    ProductAttributeFilter:
      type: object
      properties:
        filter:
          $ref: '#/components/schemas/ProductAttributeFilterFilter'
        last_id:
          description: Идентификатор последнего значения на странице. Оставьте это поле пустым при выполнении первого запроса.Чтобы получить следующие значения, укажите last_id из ответа предыдущего запроса.
          type: string
        limit:
          type: integer
          description: Количество значений на странице. Минимум — 1, максимум — 1000.
        sort_by:
          type: string
        sort_dir:
          type: string
    ProductFilter:
      type: object
      properties:
        offer_id:
          type: array
          items:
            type: string
        product_id:
          type: array
          items:
            type: string
        sku:
          type: array
          items:
            type: string
    RowItem:
      type: object
      properties:
        sku:
          type: integer
        item_code:
          type: string
        item_name:
          type: string
        free_to_sell_amount:
          type: integer
        promised_amount:
          type: integer
        reserved_amount:
          type: integer
        warehouse_name:
          type: string
    StocksItem:
      type: object
      properties:
        lastChangeDate:
          type: string
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе. Если часовой пояс не указан, то берется
            Московское время UTC+3.
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул поставщика
        techSize:
          type: string
          maxLength: 30
          description: Размер
        barcode:
          type: string
          maxLength: 30
          description: Бар-код
        quantity:
          type: integer
          description: Количество, доступное для продажи (сколько можно добавить в
            корзину)
        isSupply:
          type: boolean
          description: Договор поставки
        isRealization:
          type: boolean
          description: Договор реализации
        quantityFull:
          type: integer
          description: Полное (непроданное) количество, которое числится за складом
            (= `quantity` + в пути)
        warehouseName:
          type: string
          maxLength: 50
          description: Название склада
        nmId:
          type: integer
          description: Код WB
        subject:
          type: string
          maxLength: 50
          description: Предмет
        category:
          type: string
          maxLength: 50
          description: Категория
        daysOnSite:
          type: integer
          description: Количество дней на сайте
        brand:
          type: string
          maxLength: 50
          description: Бренд
        SCCode:
          type: string
          maxLength: 50
          description: Код контракта
        Price:
          type: number
          description: Цена
        Discount:
          type: number
          description: Скидка
    OzonError:
      type: object
      nullable: false
      properties:
        code:
          type: integer
          description: Код ошибки
        message:
          type: string
          description: Описание ошибки
        details:
          type: array
          description: Дополнительные данные, обогащающие ошибку
          items:
            type: object
            properties:
              typeUrl:
                type: string
              value:
                type: string
    Error:
      type: object
      nullable: false
      properties:
        code:
          type: string
          description: Код ошибки
          nullable: false
        message:
          type: string
          description: Описание ошибки
          nullable: false
        data:
          type: object
          description: Дополнительные данные, обогащающие ошибку
          nullable: true
  examples:
    IncorrectRequestBody:
      value:
        code: IncorrectRequestBody
        message: Некорректное тело запроса
    IncorrectRequest:
      value:
        code: IncorrectRequest
        message: Переданы некорректные данные
    IncorrectParameter:
      value:
        code: IncorrectParameter
        message: Передан некорректный параметр
  responses:
    NotFound:
      description: Запрашиваемый ресурс не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: NotFound
            message: Не найдено
    Unauthorized:
      description: Пользователь не авторизован
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: Unauthorized
            message: Пользователь не авторизован
    AccessDenied:
      description: Доступ запрещён
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: AccessDenied
            message: Доступ запрещён
    InternalServerError:
      description: Внутренняя ошибка сервиса
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: InternalServerError
            message: Внутренняя ошибка сервиса
tags:
  - name: Statistic
    description: 'Методы статистики <br><b>Лимит по запросам:</b> один запрос одного
    метода по одному токену в одну минуту. <br><br> <a href="./excel/stat-excel.html">Инструкция:
    Сохранение статистики в Excel</a>'
paths:
  /api/v1/supplier/stocks:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: [ ]
      summary: Склад WB
      operationId: getSupplierStocks
      description: Склад. Данные обновляются раз в сутки. Сервис статистики не хранит
        историю остатков товаров, поэтому получить данные об остатках товаров на прошедшую,
        не сегодняшнюю, дату - невозможно.
      tags:
        - Statistic
      parameters:
        - $ref: '#/components/parameters/dateFrom'
      responses:
        200:
          description: Список товаров на складе
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StocksItem'
              example:
                - lastChangeDate: '2022-04-28T05:57:24.787'
                  supplierArticle: '12345'
                  techSize: '48'
                  barcode: ''
                  quantity: 0
                  isSupply: false
                  isRealization: true
                  quantityFull: 3
                  warehouseName: Коледино
                  nmId: 1234567
                  subject: Брюки
                  category: Одежда
                  daysOnSite: 0
                  brand: M
                  SCCode: 3200-1234
                  Price: 5000
                  Discount: 0
  /api/v1/supplier/sales:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      operationId: getWBSales
      security:
        - HeaderApiKey: [ ]
      summary: Продажи
      description: 'Продажи. <br> Важно: гарантируется хранение данных по заказам
            не более 90 дней от даты заказа. Данные обновляются раз в 30 минут. Точное
            время обновления информации в сервисе можно увидеть в поле `lastChangeDate`.
            <br> Для идентификации товаров из одного заказа, а также продаж по ним, следует
            использовать  поле `gNumber` (строки с одинаковым значением этого поля относятся
            к одному заказу) и номер  уникальной позиции в заказе `odid` (`rid`).  <br>
            Для расчета окончательной стоимости (суммы к оплате) следует пользоваться
            следующей формулой: <br> `PriceWithDiscount = totalPrice * ((100 – discountPercent)/100)
            * ((100 – promoCodeDiscount)/100) *((100 – spp)/100)`

            '
      tags:
        - Статистика
      parameters:
        - $ref: '#/components/parameters/dateFrom'
        - $ref: '#/components/parameters/flag'
      responses:
        200:
          description: Список продаж
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SalesItem'
              example:
                - date: '2022-03-04T00:00:00'
                  lastChangeDate: '2022-03-06T10:11:07'
                  supplierArticle: '12345'
                  techSize: ''
                  barcode: '123453559000'
                  totalPrice: 0
                  discountPercent: 0
                  isSupply: false
                  isRealization: true
                  promoCodeDiscount: 0
                  warehouseName: Подольск
                  countryName: Россия
                  oblastOkrugName: Центральный федеральный округ
                  regionName: Московская
                  incomeID: 0
                  saleID: D99937000247
                  odid: 456739003897
                  spp: 0
                  forPay: 0
                  finishedPrice: 0
                  priceWithDisc: 0
                  nmId: 1234567
                  subject: Мультистайлеры
                  category: Бытовая техника
                  brand: Тест
                  IsStorno: 0
                  gNumber: '34343462218572569531'
                  sticker: ''
        429:
          description: Слишком много запросов
        400:
          description: Ошибка в запросе
          content:
            application/json:
              example:
                errors:
                  - can't parse dateFrom
  /api/v1/supplier/orders:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      operationId: getWBOrders
      security:
        - HeaderApiKey: [ ]
      summary: Заказы
      description: "Заказы. <br>  Важно: гарантируется хранение данных по заказам\
          \ не более 90 дней от даты заказа. Данные обновляются раз в 30 минут.  Точное\
          \ время обновления информации в сервисе можно увидеть в поле `lastChangeDate`.\
          \ <br> Для идентификации товаров из одного заказа, а также продаж по ним,\
          \ следует использовать  поле `gNumber` (строки с одинаковым значением этого\
          \ поля относятся к одному заказу) и номер  уникальной позиции в заказе `odid`\
          \ (`rid`). \n"
      tags:
        - Статистика
      parameters:
        - $ref: '#/components/parameters/dateFrom'
        - $ref: '#/components/parameters/flag'
      responses:
        200:
          description: Список заказов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdersItem'
              example:
                - date: '2022-03-02T14:34:05'
                  lastChangeDate: '2022-03-02T19:30:16'
                  supplierArticle: '12345'
                  techSize: '0'
                  barcode: '9990016520011'
                  totalPrice: 120.56
                  discountPercent: 0
                  warehouseName: Екатеринбург
                  oblast: Московская
                  incomeID: 123456
                  odid: 12345678
                  nmId: 12345678
                  subject: Респираторы
                  category: Спецодежда и СИЗы
                  brand: wildberries
                  isCancel: false
                  cancel_dt: '0001-01-01T00:00:00'
                  gNumber: '12345678'
                  sticker: ''
        429:
          description: Слишком много запросов
        400:
          description: Ошибка в запросе
          content:
            application/json:
              example:
                errors:
                  - can't parse dateFrom
  /v2/analytics/stock_on_warehouses:
    servers:
      - url: https://api-seller.ozon.ru/
    post:
      summary: Склад OZON
      operationId: getOzonSupplierStocks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                warehouse_type:
                  type: string
                  enum:
                    - EXPRESS_DARK_STORE
                    - NOT_EXPRESS_DARK_STORE
                    - ALL
                limit:
                  type: integer
                offset:
                  type: integer
      responses:
        200:
          description: Список товаров на складе
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      rows:
                        type: array
                        items:
                          $ref: '#/components/schemas/RowItem'
  /v2/product/info/list:
    servers:
      - url: https://api-seller.ozon.ru/
    post:
      summary: Склад OZON
      operationId: getOzonProductInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductFilter'
      responses:
        200:
          description: Список информации о товаре
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/ProductInfo'
  /v3/products/info/attributes:
    servers:
      - url: https://api-seller.ozon.ru/
    post:
      summary: Атрибуты продукта
      operationId: getOzonProductAttributes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductAttributeFilter'
      responses:
        200:
          description: Список информации о товаре
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_id:
                    type: string
                  total:
                    type: integer
                  result:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductAttribute'
        404:
          description: Ответ не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OzonError'
